### ISSUE TITLE
Validação do campo de CPF

### ISSUE THREAD

**Issue by brenofranca83** [ESEGroup/mytinyPoll#3]
Nós formulários contendo o campo de CPF para preenchimento, é necessária a validação do mesmo de acordo com o cálculo do CPF.
Ver exemplo em: http://www.dicasdeprogramacao.com.br/algoritmo-para-validar-cpf/

**Comment by Hguimaraes** [comment]
Implementado pela @vercoza e a equipe 2. Está em "Validator" -> "cpf_validator.rb".
* Commit 58e41f8de11
